### ISSUE TITLE
Any chance on a hires version

### ISSUE THREAD

**Issue by aquatix** [Ken-Vermette/Bridge-Cursor#2]
I love your cursor theme and have been rocking it for quite a while now. I now have a hidpi laptop on which they are really tiny though. My eyes are good, but if they could switch to a highres version on that kind of screens, that would be really awesome.

Thanks for the theme either way :)

**Comment by Ken-Vermette** [comment]
There is actually already high-res versions available; In terms of his branch, I'll be overhauling it soon. For now, you can get high-res versions here:
https://share.kde.org/public.php?service=files&t=126262cfb84b85175690483d7e3f2638

You'll want "plasma-cursors-breeze-compiled-2.1", but there are many others to choose from. The "Source" versions are basically what I'll be uploading here, only I'm going to update the scripts a bit first.

You may need to manually set the cursor size after you get them.

**Comment by aquatix** [comment]
Oh cool, didn't know that. I'll try it out shortly, thanks!
