### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by bluishmatt** [Ken-Vermette/Bridge-Cursor#4]
Hi, I'd like to use this cursor in Windows however it is only 21x13 pixels.  The original windows one is 75x49, which make this cursor tiny. Could you possibly upload higher resolution PNG's? Or upload the original file in which ever program these were made in (so they can be scaled)?

**Comment by Ken-Vermette** [comment]
Hello!
So this was opened and closed before I could react; is there anything needed here? :)

**Comment by bluishmatt** [comment]
Hey, I found another called breeze snow: https://asfhy.deviantart.com/art/Breeze-Snow-for-Windows-607322264

I prefer the dark grey one you have though, and after looking at breeze snow it seems the canvas size of yours is what makes it look smaller (42x42). When I have time later I will crop the canvas down to 32x32 and see if that works.

Matt

Sent from Mail for Windows 10

**Comment by bluishmatt** [comment]
Sent from Mail for Windows 10
